# This file is placed in the Public Domain.


[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "nixm"
version = "6"
authors = [
    {name = "Bart Thate", email = "record11719@gmail.com" },
]
description = "Nix Em"
readme = "README.rst"
license = { text="Public Domain"}
classifiers=[
    'Development Status :: 4 - Beta',
    'License :: Public Domain',
    'Operating System :: Unix',
    'Programming Language :: Python :: 3',
    'Topic :: Utilities'
]


[project.urls]
"home" = "https://pypi.org/project/nixm"
"bugs" = "https://github.com/otpcr/nixm/issues"
"source" = "https://github.com/otpcr/nixm"


[tool.setuptools]
script-files = [
    'bin/nixm',
]
packages = [
   'nixm',
]


[tool.setuptools.data-files]
"share/nixm/mods/" = [
    'mods/__init__.py',
    'mods/cmd.py',
    'mods/err.py',
    'mods/fnd.py',
    'mods/irc.py',
    'mods/log.py',
    'mods/mod.py',
    'mods/opm.py',
    'mods/req.py',
    'mods/rss.py',
    'mods/srv.py',
    'mods/tdo.py',
    'mods/thr.py',
    'mods/upt.py'
]

