# This file is placed in the Public Domain.


NAMES = {
    "cmd": "nixm.modules.cmd",
    "err": "nixm.modules.err",
    "flt": "nixm.modules.flt",
    "fnd": "nixm.modules.fnd",
    "cfg": "nixm.modules.irc",
    "mre": "nixm.modules.irc",
    "pwd": "nixm.modules.irc",
    "log": "nixm.modules.log",
    "cor": "nixm.modules.mbx",
    "eml": "nixm.modules.mbx",
    "mbx": "nixm.modules.mbx",
    "dis": "nixm.modules.mdl",
    "now": "nixm.modules.mdl",
    "mod": "nixm.modules.mod",
    "req": "nixm.modules.req",
    "dpl": "nixm.modules.rss",
    "exp": "nixm.modules.rss",
    "imp": "nixm.modules.rss",
    "nme": "nixm.modules.rss",
    "rem": "nixm.modules.rss",
    "res": "nixm.modules.rss",
    "rss": "nixm.modules.rss",
    "syn": "nixm.modules.rss",
    "lne": "nixm.modules.slg",
    "slg": "nixm.modules.slg",
    "dne": "nixm.modules.tdo",
    "tdo": "nixm.modules.tdo",
    "thr": "nixm.modules.thr",
    "tmr": "nixm.modules.tmr",
    "udp": "nixm.modules.udp",
    "upt": "nixm.modules.upt",
    "wsd": "nixm.modules.wsd"
}
